[BASIC]
; progenitor distance
distance: 10 kpc
; simulation energy grid
Emin: 0 MeV
Emax: 100 MeV
dE:   100 keV
; simulation time grid
tmin: -1 s
tmax:  1 s
dt:    1 ms
; result time grid: resolution and offset
dt_res: 2 ms
toff_res: 0 s

[MODEL]
; model type (presn, ccsn, ...)
type: snewpy.models.ccsn
; model parameters:
name: Nakazato_2013
progenitor_mass: 13 Msun
revival_time: 300 ms
metallicity: 0.004
eos: shen

[XFORM]
transformations: AdiabaticMSW
order: Normal
mixing: NuFIT6.0

[DETECTOR]
detector_scope: IC86
add_wls: True
