# This is a basic workflow to help you get started with Actions
# This workflow was originally taken from the NEWS2/snewpy repository

name: tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
      - release_*
  pull_request:
      - main
      - release_*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        # Test all supported Python versions under Ubuntu
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
        # Test one version under MacOS X and Windows
        include:
          - os: macos-latest
            python-version: '3.12'
          - os: windows-latest
            python-version: '3.12'

    # The type of runner used for the job.
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up the Python environment and dependencies
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install ASTERIA
        run: |
          pip install ".[dev]"

      # Run the unit tests
      - name: Test with pytest
        run: |
          pytest
